spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30

resilience4j.retry:
  instances:
    service:
      maxRetryAttempts: 5
      waitDuration: 1000 #in milliseconds


feign:
  circuitbreaker:
    enabled: true
