spring:
  application:
    name: gateway

  cloud:
    loadbalancer:
      cache:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 30
